services:
    database:
        image: mysql:5.7
        restart: on-failure
        environment:
            - MYSQL_ALLOW_EMPTY_PASSWORD=true
        volumes:
            - database_data:/var/lib/mysql
            - database_config:/etc/mysql/conf.d
    mail:
        image: ajoergensen/mailhog:latest
        restart: on-failure
        ports:
            - 8025:8025
    web:
        build:
            context: .
            target: debug # base | debug
            # args:
            # with defaults:
            # - UNAME=dev
            # - UID=1000
            # - GID=1000
            # - NODE_VERSION=16.14.2
            # - NODE_ARCH=linux-x64
            # - XDEBUG_MODE=coverage,profile
        restart: on-failure
        depends_on:
            - database
            - mail
        links:
            - "database:database"
            - "mail:mail"
        ports:
            - 80:80
            - 443:443
        volumes:
            - ./:/var/www

volumes:
    database_data:
    database_config:
