version: "3.8"

services:
    database:
        image: mariadb:10.5
        restart: on-failure
        ports:
            - 3308:3306
        environment:
            - MYSQL_ROOT_PASSWORD=
            - MYSQL_ALLOW_EMPTY_PASSWORD=true
            - MYSQL_USER=dev
            - MYSQL_PASSWORD=dev
            - MYSQL_DATABASE=app
        volumes:
            - database_data:/var/lib/mysql
            - database_config:/etc/mysql/conf.d
    web:
        build:
            context: .
            args:
                - NODE_VERSION=16.14.2
                - NODE_ARCH=linux-x64
        restart: on-failure
        links:
            - "database:database"
        ports:
            - 8080:80
            - 8443:443
        volumes:
            - ./:/var/www

volumes:
    database_data:
    database_config:
