services:
    database:
        image: mysql:5.7
        restart: on-failure
        environment:
            - MYSQL_ALLOW_EMPTY_PASSWORD=true
        volumes:
            - database_data:/var/lib/mysql
            - database_config:/etc/mysql/conf.d
        ports:
            - 3306:3306
    mail:
        image: ajoergensen/mailhog:latest
        restart: on-failure
        ports:
            - 8025:8025

    web:
        build:
            context: .
            target: debug # base | debug
            # args:
            # with defaults:
            # - UNAME=dev
            # - UID=1000
            # - GID=1000
            # - NODE_VERSION=18.x.x
            # - NODE_ARCH=linux-x64
        environment:
            # set the `XDEBUG_MODE` env in your shell, than start or restart your container:
            #
            # `export XDEBUG_MODE=<mode>` where mode is a comma-separated combination from:
            #   `off|develop|debug|coverage|profile|trace`
            # `XDEBUG_MODE` defaults to `off`
            #
            # the xdebug output dir is set to './docker/tmp'.
            XDEBUG_MODE: ${XDEBUG_MODE:-off}
        restart: on-failure
        depends_on:
            - database
            - mail
        links:
            - "database:database"
            - "mail:mail"
        ports:
            - 80:80
            - 443:443
        volumes:
            - ./:/var/www
            - ./docker/tmp:/tmp
        extra_hosts:
            - "host.docker.internal:host-gateway"

volumes:
    database_data:
    database_config:
