version: "3.8"

services:
    db:
        image: mysql:5.7
        environment:
            - MYSQL_ROOT_PASSWORD=secret
            - MYSQL_PASSWORD=secret
            - MYSQL_DATABASE=app_db
            - MYSQL_USER=app
    web:
        build: .
        ports:
            - 8080:80
