version: "3.8"

services:
    database:
        image: mysql:8.0.28
        ports:
            - 3308:3306
        environment:
            - MYSQL_ROOT_PASSWORD=
            - MYSQL_ALLOW_EMPTY_PASSWORD=true
            - MYSQL_USER=dev
            - MYSQL_PASSWORD=dev
            - MYSQL_DATABASE=app
        volumes:
            - mysql_data:/var/lib/mysql
            - mysql_config:/etc/mysql/conf.d
    web:
        build: .
        links:
            - "database:database"
        ports:
            - 8080:80
            - 8443:443
        volumes:
            - ./:/var/www

volumes:
    mysql_data:
    mysql_config:
